plugins {
    id 'com.android.application'
}

android {
    namespace 'com.genymobile.scrcpy.android'
    compileSdk 36

    defaultConfig {
        applicationId 'com.genymobile.scrcpy.android'
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName '0.1.0'

        externalNativeBuild {
            cmake {
                cppFlags ''
                arguments '-DANDROID_STL=c++_shared'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }
}

dependencies {
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.10.2'
}
